deployment:
  tasks:
    - export REPOPATH=/home/colorkob/color-kobrin/*
    - export SITEPATH=/home/colorkob/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
