deployment:
  tasks:
    - export REPOPATH=/home/colorkob/repositories/color-kobrin/*
    - export SITEPATH=/home/colorkob/color_app/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
